### ISSUE TITLE
能否给出评估的代码展示

### ISSUE THREAD

**Issue by Jack-Yang-S** [fzp0424/self_correct_mt#2]
作者您好，我复现了您给出的代码。我注意到论文中评价打分的内容也非常多，但是代码却没有一些展示，能否给出一些评价打分的简单的代码和展示，让整体的代码工作更完整

**Comment by fzp0424** [comment]
@Jack-Yang-S -抱歉前段时间在进行其他的项目。因为内容有点多，evaluation code 会在emnlp结束之后整理出来。
-I'm sorry I'm working on other projects at this period. Because the data and code are a little too much, the evaluation code will be released out after the end of EMNLP.

**Comment by Jack-Yang-S** [comment]
EMNLP is the best NLP conference in the world?

**Comment by fzp0424** [comment]
> EMNLP is the best NLP conference in the world?

Hhh, I think so.

**Comment by fzp0424** [comment]
@Jack-Yang-S Please check our latest version of this repo. We have added our evaluation code and cases in `./eval`
